//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Calculator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalcData", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CalcData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurSignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlagequalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MemoryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrevNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurSign {
            get {
                return this.CurSignField;
            }
            set {
                if ((object.ReferenceEquals(this.CurSignField, value) != true)) {
                    this.CurSignField = value;
                    this.RaisePropertyChanged("CurSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurValue {
            get {
                return this.CurValueField;
            }
            set {
                if ((this.CurValueField.Equals(value) != true)) {
                    this.CurValueField = value;
                    this.RaisePropertyChanged("CurValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((this.FlagField.Equals(value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flagequal {
            get {
                return this.FlagequalField;
            }
            set {
                if ((this.FlagequalField.Equals(value) != true)) {
                    this.FlagequalField = value;
                    this.RaisePropertyChanged("Flagequal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputValue {
            get {
                return this.InputValueField;
            }
            set {
                if ((object.ReferenceEquals(this.InputValueField, value) != true)) {
                    this.InputValueField = value;
                    this.RaisePropertyChanged("InputValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MemoryValue {
            get {
                return this.MemoryValueField;
            }
            set {
                if ((this.MemoryValueField.Equals(value) != true)) {
                    this.MemoryValueField = value;
                    this.RaisePropertyChanged("MemoryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrevNum {
            get {
                return this.PrevNumField;
            }
            set {
                if ((this.PrevNumField.Equals(value) != true)) {
                    this.PrevNumField = value;
                    this.RaisePropertyChanged("PrevNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calculator.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/GetData", ReplyAction="http://tempuri.org/ICalculator/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ICalculator/GetDataUsingDataContractResponse")]
        Client.Calculator.CompositeType GetDataUsingDataContract(Client.Calculator.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/clck", ReplyAction="http://tempuri.org/ICalculator/clckResponse")]
        Client.Calculator.CalcData clck(Client.Calculator.CalcData cd, string btn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/memory", ReplyAction="http://tempuri.org/ICalculator/memoryResponse")]
        void memory(Client.Calculator.CalcData cd, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/act", ReplyAction="http://tempuri.org/ICalculator/actResponse")]
        void act(Client.Calculator.CalcData cd, string curSign_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/setValue", ReplyAction="http://tempuri.org/ICalculator/setValueResponse")]
        void setValue(Client.Calculator.CalcData cd, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/getValue", ReplyAction="http://tempuri.org/ICalculator/getValueResponse")]
        double getValue(Client.Calculator.CalcData cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/bckspc", ReplyAction="http://tempuri.org/ICalculator/bckspcResponse")]
        Client.Calculator.CalcData bckspc(Client.Calculator.CalcData cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/ce", ReplyAction="http://tempuri.org/ICalculator/ceResponse")]
        Client.Calculator.CalcData ce(Client.Calculator.CalcData cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/c", ReplyAction="http://tempuri.org/ICalculator/cResponse")]
        Client.Calculator.CalcData c(Client.Calculator.CalcData cd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : Client.Calculator.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<Client.Calculator.ICalculator>, Client.Calculator.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Client.Calculator.CompositeType GetDataUsingDataContract(Client.Calculator.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public Client.Calculator.CalcData clck(Client.Calculator.CalcData cd, string btn) {
            return base.Channel.clck(cd, btn);
        }
        
        public void memory(Client.Calculator.CalcData cd, string action) {
            base.Channel.memory(cd, action);
        }
        
        public void act(Client.Calculator.CalcData cd, string curSign_) {
            base.Channel.act(cd, curSign_);
        }
        
        public void setValue(Client.Calculator.CalcData cd, double value) {
            base.Channel.setValue(cd, value);
        }
        
        public double getValue(Client.Calculator.CalcData cd) {
            return base.Channel.getValue(cd);
        }
        
        public Client.Calculator.CalcData bckspc(Client.Calculator.CalcData cd) {
            return base.Channel.bckspc(cd);
        }
        
        public Client.Calculator.CalcData ce(Client.Calculator.CalcData cd) {
            return base.Channel.ce(cd);
        }
        
        public Client.Calculator.CalcData c(Client.Calculator.CalcData cd) {
            return base.Channel.c(cd);
        }
    }
}
